feat: Add warning message when tsconfig is invalid
SukkaW/rollup-plugin-swc pull request #45
Opened 2023-09-06 03:39 UTC by citrus327

Add warning message when tsconfig is invalid

2023-09-06 08:30 UTC, SukkaW requested changes

2023-09-06 08:30 UTC, SukkaW commented on src/options.ts
>    }
```suggestion
  if (!result && !tsconfig) {
    console.warn('[rollup-plugin-swc] tsconfig does not exists, fallback to jsconfig.json');
    result = getTsconfig(cwd, 'jsconfig.json');
  }
```

2023-09-06 08:32 UTC, SukkaW commented on src/options.ts
>    }
Also, IMHO we should use rollup built-in log functions here: https://rollupjs.org/plugin-development/#this-warn

2023-09-11 05:50 UTC, citrus327 commented
@SukkaW I've updated the changes, please review again, thank you.

2023-09-11 08:18 UTC, SukkaW commented on src/options.ts
> +    ctx.warn('tsconfig does not exists, fallback to jsconfig.json');
```suggestion
    ctx.warn({
      message: 'Can\'t find tsconfig.json, trying jsconfig.json',
      pluginCode: 'SWC_TSCONFIG_NOT_EXISTS'
    });
```

2023-09-11 08:25 UTC, merged